# Generated by Django 5.2 on 2025-05-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_color_vehiculo_combustible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/adicionales/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Imagen Adicional',
                'verbose_name_plural': 'Imágenes Adicionales',
                'ordering': ['orden'],
            },
        ),
    ]
